### ISSUE TITLE
Not Home zone getting overridden in 2.0rc7

### ISSUE THREAD

**Issue by manonstreet** [gcobb321/icloud3_dev#4]
Since upgrading to 2.0rc7, iCloud3 no longer shows me as away when exiting my home zone.  I see a not_home event in connection with an `IOS App v2 update started, GPS (xxxx, yyyy)`.  And then immediately after I see a `Retrying last update` and it calls and a `__Trigger change detected, iBeacon Region Entered@` and a timestamp that is 9 minutes prior to the new GPS coordinates.  This then sets me back to the home zone.  I see this sequence repeating each time IOS App v2 updates my coordinates - I get reset back to home from a much older event.  So according to the device_tracker state, I have never left home.

**Comment by gcobb321** [comment]
Do you see a Geographic Region Exit event when you leave home? If iCloud3 doesn’t get an exit event, it thinks the new location is due to gps wandering and puts you back in the home zone. ReTrying the last update might mean there was some type of error encountered (bad gps, old location, iCloud, program, etc) that might also be causing the problem. 

 I have released v2.0 and have added more debug logging to the event log that can be turned on and off using the icloud3_update service call. That might give some more info about the trigger changes that are now getting picked up. Can you copy the text from the Event Log showing the sequence of events?

Go [here](https://github.com/gcobb321/iCloud3) to get it.

**Comment by manonstreet** [comment]
Upgraded to 2.0.  At first I couldn't get the iCloud3 Event Log to refresh and it was throwing an invalid service error on device_tracker.icloud_update.  After resetting the front end cache in the IOS v2 app, that error cleared.  I enabled debug logging - but now I cannot reproduce the issue I was having with rc7.  It seems to be tracking state changes correctly.  I'll keep an eye on it and report back...but for now, all good.

**Comment by manonstreet** [comment]
Everything still working.  Closing this issue.
